export interface Item {
  id: string;
  text: string;
  flies: boolean;
  image?: string;
}

export const ITEMS: Item[] = [
  { id: 'eagle', text: 'Eagle 🦅', flies: true },
  { id: 'pigeon', text: 'Pigeon 🐦', flies: true },
  { id: 'sparrow', text: 'Sparrow 🐦', flies: true },
  { id: 'crow', text: 'Crow 🐦', flies: true },
  { id: 'parrot', text: 'Parrot 🦜', flies: true },
  { id: 'owl', text: 'Owl 🦉', flies: true },
  { id: 'peacock', text: 'Peacock 🦚', flies: true },
  { id: 'duck', text: 'Duck 🦆', flies: true },
  { id: 'swan', text: 'Swan 🦢', flies: true },
  { id: 'eagle-kite', text: 'Kite (toy) 🪁', flies: true },
  { id: 'bat', text: 'Bat 🦇', flies: true },
  { id: 'butterfly', text: 'Butterfly 🦋', flies: true },
  { id: 'bee', text: 'Bee 🐝', flies: true },
  { id: 'dragonfly', text: 'Dragonfly', flies: true },
  { id: 'mosquito', text: 'Mosquito 🦟', flies: true },
  { id: 'ladybug', text: 'Ladybug 🐞', flies: true },
  { id: 'helicopter', text: 'Helicopter 🚁', flies: true },
  { id: 'plane', text: 'Airplane ✈️', flies: true },
  { id: 'rocket', text: 'Rocket 🚀', flies: true },
  { id: 'ufo', text: 'UFO 🛸', flies: true },
  { id: 'hotair', text: 'Hot Air Balloon 🎈', flies: true },
  { id: 'paperplane', text: 'Paper Plane', flies: true },
  { id: 'balloon', text: 'Helium Balloon 🎈', flies: true },
  { id: 'leaf', text: 'Falling Leaf 🍃', flies: true },
  { id: 'feather', text: 'Feather 🪶', flies: true },
  { id: 'frisbee', text: 'Frisbee 🥏', flies: true },
  { id: 'drone', text: 'Drone 🛩️', flies: true },
  { id: 'glider', text: 'Glider', flies: true },
  { id: 'kitebird', text: 'Black Kite (bird)', flies: true },
  { id: 'penguin', text: 'Penguin 🐧', flies: false },
  { id: 'ostrich', text: 'Ostrich 🐦‍⬛', flies: false },
  { id: 'emu', text: 'Emu', flies: false },
  { id: 'chicken', text: 'Chicken 🐔', flies: false },
  { id: 'turkey', text: 'Turkey 🦃', flies: false },
  { id: 'dog', text: 'Dog 🐶', flies: false },
  { id: 'cat', text: 'Cat 🐱', flies: false },
  { id: 'cow', text: 'Cow 🐄', flies: false },
  { id: 'buffalo', text: 'Buffalo', flies: false },
  { id: 'horse', text: 'Horse 🐴', flies: false },
  { id: 'goat', text: 'Goat 🐐', flies: false },
  { id: 'sheep', text: 'Sheep 🐑', flies: false },
  { id: 'elephant', text: 'Elephant 🐘', flies: false },
  { id: 'lion', text: 'Lion 🦁', flies: false },
  { id: 'tiger', text: 'Tiger 🐯', flies: false },
  { id: 'bear', text: 'Bear 🐻', flies: false },
  { id: 'rabbit', text: 'Rabbit 🐰', flies: false },
  { id: 'snake', text: 'Snake 🐍', flies: false },
  { id: 'turtle', text: 'Turtle 🐢', flies: false },
  { id: 'frog', text: 'Frog 🐸', flies: false },
  { id: 'whale', text: 'Whale 🐋', flies: false },
  { id: 'dolphin', text: 'Dolphin 🐬', flies: false },
  { id: 'shark', text: 'Shark 🦈', flies: false },
  { id: 'ant', text: 'Ant 🐜', flies: false },
  { id: 'spider', text: 'Spider 🕷️', flies: false },
  { id: 'crab', text: 'Crab 🦀', flies: false },
  { id: 'lobster', text: 'Lobster 🦞', flies: false },
  { id: 'octopus', text: 'Octopus 🐙', flies: false },
  { id: 'fish', text: 'Fish 🐟', flies: false },
  { id: 'stone', text: 'Stone 🪨', flies: false },
  { id: 'rock', text: 'Rock', flies: false },
  { id: 'car', text: 'Car 🚗', flies: false },
  { id: 'bus', text: 'Bus 🚌', flies: false },
  { id: 'train', text: 'Train 🚆', flies: false },
  { id: 'ship', text: 'Ship 🚢', flies: false },
  { id: 'submarine', text: 'Submarine', flies: false },
  { id: 'bicycle', text: 'Bicycle 🚲', flies: false },
  { id: 'motorbike', text: 'Motorbike 🏍️', flies: false },
  { id: 'scooter', text: 'Scooter 🛵', flies: false },
  { id: 'skateboard', text: 'Skateboard 🛹', flies: false },
  { id: 'chair', text: 'Chair 🪑', flies: false },
  { id: 'table', text: 'Table', flies: false },
  { id: 'sofa', text: 'Sofa 🛋️', flies: false },
  { id: 'bed', text: 'Bed 🛏️', flies: false },
  { id: 'book', text: 'Book 📘', flies: false },
  { id: 'phone', text: 'Phone 📱', flies: false },
  { id: 'laptop', text: 'Laptop 💻', flies: false },
  { id: 'camera', text: 'Camera 📷', flies: false },
  { id: 'cup', text: 'Cup 🥤', flies: false },
  { id: 'ball', text: 'Ball ⚽', flies: false },
  { id: 'umbrella', text: 'Umbrella ☂️', flies: false },
  { id: 'key', text: 'Key 🔑', flies: false },
  { id: 'clock', text: 'Clock ⏰', flies: false },
  { id: 'guitar', text: 'Guitar 🎸', flies: false },
  { id: 'piano', text: 'Piano 🎹', flies: false },
  { id: 'drum', text: 'Drum 🥁', flies: false }
];
